services:
  web:
    build: ./abbybot_website
    command: gunicorn --bind 0.0.0.0:5001 wsgi:app
    volumes:
      - ./abbybot_website:/app
    ports:
      - "5001:5001"
    env_file:
      - ./abbybot_website/.env
    restart: always
