version: '3.8'

services:
  web:
    build: ./abbybot_website
    command: gunicorn --bind 0.0.0.0:5010 wsgi:app
    volumes:
      - ./abbybot_website:/app
    ports:
      - "5010:5010"
    env_file:
      - ./abbybot_website/.env

volumes:
  db_data:
